require("config.settings")
require("config.lazy")
require("config.keybindings")
require("config.harpoon_config")
require("autocommands.general_autocmds")
require("autocommands.no_neck_pain_autocmds")
